services:
  autonity:
    image: ${AUTONITY_IMAGE}
    container_name: autonity
    command: >
      --datadir /autonity-chaindata
      --bakerloo
      --syncmode full 
      --http
      --http.addr 0.0.0.0
      --http.api aut,eth,net,txpool,web3,admin
      --http.vhosts *
      --ws
      --ws.addr 0.0.0.0
      --ws.api aut,eth,net,txpool,web3,admin
      --nat extip:${YOURIP}
    volumes:
      - $HOME/autonity-chaindata:/autonity-chaindata
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "30303:30303/udp"
      - "6060:6060"
      - "20203:20203/tcp"
      - "20203:20203/udp"
    stdin_open: true
    tty: true
    stop_grace_period: 180s

  oracle:
    image: ${ORACLE_IMAGE}
    container_name: oracle
    command: ["/autoracle/oracle_config.yml"] 
    volumes:
      - $HOME/.autonity/keystore/oracle.key:/autoracle/oracle.key
      - $HOME/.autonity/oracle/oracle_config.yml:/autoracle/oracle_config.yml
    stdin_open: true
    tty: true
    stop_grace_period: 180s
    depends_on:
      - autonity

networks:
  autonity_network:
    driver: bridge